### PR TITLE
Awesome, that's exactly what i need.

### PR DESCRIPTION
**Pull request by Lanfei**
Awesome, that's exactly what i need.

But there are some problems:
1. Because of a little mistake (699133a08576c5555a2fbe2d93af235ba937eaf6), it didn't work when the `publicPath` is not provided.
2. It didn't work either when I put my assets in a sub folder, so I add the `dirs` option to support this case (730311edcca5760930fd95228139e2b6281670db).
3. There some indents using spaces, but others are using tabs, so I format codes by WebStorm (84f05ac5eb7a0529f840f3445f48f4730a86481f).

英文不太好，请指正→_→

### CODE REVIEW

**Comment by zhex** [comment]
Hi, thank you for your PR.
It seems you separate the css and js in the different folder. So it will have different ext name in each folder. I am not sure the following code works for you or not.

``` js
new PagePlugin({
    cwd: __dirname + '/src',
    files: '{css,js}/**/*.{jsx,css}',
    outputPageName: function (filename) {
        return filename;
    }, 
    entryName: function (name) {
        return name;
    }
})
```

**Comment by Lanfei** [comment]
It didn't work..

It seems the `files` option should be HTML files, am I right?

**Comment by zhex** [comment]
@Lanfei Yes, you are right.
Could you let me know there is any reason you should copy js and css files without through webpack loader? that is what webpack do originally.

**Comment by Lanfei** [comment]
I add the `dirs` option to replace references in HTML files correctly, but not to copy js or css files.

This is my directory structure:

```
|- dist
|- |- css
|- |- |- index.css
|- |- js
|- |- |- index.js
|- |- index.html
|- src
|- |- css
|- |- |- index.css
|- |- js
|- |- |- index.js
|- |- index.html
```

So, my codes in `src/index.html` are:

``` html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Demo</title>
    <link rel="stylesheet" href="css/index.css">
</head>
<body>
<script src="js/index.js"></script>
</body>
</html>
```

But the plugin could only match `index.css` and `index.js`, but not `css/index.css` and `js/index.js`.

**Comment by zhex** [comment]
@Lanfei 

Ok, i understand now.

Actually, this plugin using the entry names for the css and js file, so you just need to set the entry name with different extensions in the html file. This will keep the plugin simple. If you want to change the output path, you can do it `output.filename` or  in loaders, which you can find in the example I pasted in readme.

**Comment by Lanfei** [comment]
However, this bug (699133a08576c5555a2fbe2d93af235ba937eaf6) really need to be fixed.

**Comment by Lanfei** [comment]
And..

May I have your QQ number= =?

**Comment by zhex** [comment]
@Lanfei 
Yes，this is really a bug, Could you separate the pull request?

**Comment by Lanfei** [comment]
Okay, I did.

**Pull request closed without merging**
